apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: web
        image: ubuntu
        command: "python3 manage.py runserver 8080"
---

apiVersion: v1
kind: Service
metadata:
  name: web
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: web
    port: 8080
  selector:
    app: web
